export const tenant = { name: 'א. אמיר גז בע״מ', phone: '04-0000000', address: 'אזור התעשייה, ואדי ערה' };
export const today = '2026-09-13';
export const areas = ['אום אל-פחם','ערערה','כפר קרע','באקה אל-גרבייה','פרדס חנה','חריש','חדרה','קציר','ואדי ערה'];
export const statuses = ['חדשה','ממתינה לאישור נהג','שויכה','בדרך','בחלוקה','בוצעה','שולמה','נסגרה','בוטלה'];
export const methods = ['אשראי','מזומן',"צ'ק",'העברה בנקאית','שולם באתר'];
export const categories = ['בלון 12 ק״ג','בלון 48 ק״ג','מחמם מים','לקוחות עסקיים','טכנאי','VIP','לקוחות רדומים','לקוחות חדשים'];
export interface Customer {id:number;name:string;phone:string;email:string;area:string;address:string;category:string;debt:number;entry:string;notes:string;priceList?:string;customPrices?:Record<number,number>;forecastDays?:number;forecastManual?:boolean}
export interface Order {id:number;customerId:number;productId:number;quantity:number;driverId:number|null;date:string;window:string;payment:string;status:string;amount:number;paid:boolean;delivered:boolean;document:string;address:string;assignedAt?:string;driverOpenedAt?:string;driverAcknowledgedAt?:string;closedAt?:string;returned12?:number;returned48?:number}
export interface Driver {id:number;name:string;area:string;vehicleId:number;phone:string;status:string;score:number;collected:number;priceList?:string;customPrices?:Record<number,number>}
export interface Product {id:number;name:string;sku:string;weight:number;cost:number;price:number;contractor:number;minimum:number;supplierId:number}
export interface Stock {id:number;name:string;full12:number;empty12:number;full48:number;empty48:number;other:number}
export interface Notice {id:number;title:string;category:string;severity:string;target:string;entityId:number;read:boolean;muted:boolean;deferred:boolean}
export interface Audit {id:number;time:string;user:string;module:string;action:string;entity:string;before:string;after:string;device:string}
export interface Service {id:number;customerId:number;technicianId:number;type:string;date:string;time:string;status:string;priority:string}
const names = ['משפחת כהן','אחמד מחאמיד','מרים ג׳בארין','מסעדת אל ואדי','יעל לוי','חאלד אגבאריה','דנה ישראלי','עלי יונס','נועה אברהם','מאפיית הכפר','סמיר חטיב','רונית מזרחי','פאטמה אבו סאלח','אורן ברק','משפחת דראושה','יוסי כהן','יוסף כהן','לינא מסארווה','אמיר חדד','מיכל פרידמן','נדים מחאמיד','משפחת ביטון','חסן ג׳בארין','רותם שפירא'];
export const initialCustomers:Customer[] = names.map((name,i)=>({id:i+1,name,phone:`050-000${String(i===16?15:i).padStart(4,'0')}`,email:`demo${i+1}@example.invalid`,area:areas[i%9],address:`רחוב הזית ${i+4}, ${areas[i%9]}`,category:categories[i%8],debt:i%4===0?430*(i%3+1):0,entry:i%3===0?'1234':'ללא קוד',notes:'הבלונים בחצר האחורית. יש לתאם הגעה מראש.',forecastDays:180,forecastManual:false}));
export const initialDrivers:Driver[] = ['מוחמד אבו סאלח','עבד מחאמיד','אחמד ג׳בארין','יוסי כהן','רמי לוי','מחמוד אגבאריה','עלי מחאמיד','סמיר ג׳בארין'].map((name,i)=>({id:i+1,name,area:areas[i],vehicleId:i%5+1,phone:`052-00000${20+i}`,status:'פעיל',score:98-i*2,collected:i===0?3280:1560+i*120}));
export const initialProducts:Product[] = ['בלון 12 ק״ג','בלון 48 ק״ג','מחמם מים','וסת','צינור גז','כירת גז'].map((name,i)=>({id:i+1,name,sku:`GAS-${101+i}`,weight:[12,48,0,0,0,0][i],cost:[90,290,1600,45,12,230][i],price:[160,430,2400,95,35,390][i],contractor:[140,390,2100,75,25,320][i],minimum:[60,40,5,20,40,5][i],supplierId:i<2?1:i<4?2:3}));
export const initialOrders:Order[] = Array.from({length:37},(_,i)=>{const customer=initialCustomers[i%24];const product=initialProducts[i%6===0?0:1];return {id:10421+i,customerId:customer.id,productId:product.id,quantity:i===0?2:1+i%2,driverId:i<4?null:i%8+1,date:today,window:['08:00–10:00','10:00–12:00','12:00–14:00','14:00–16:00'][i%4],payment:methods[i%5],status:i>=13?'בוצעה':statuses[i%5],amount:product.price*(i===0?2:1+i%2),paid:i>=13&&i<31,delivered:i>=13,document:i>=13&&i<31?`קבלה ${8000+i}`:'',address:customer.address,assignedAt:i<4?undefined:`2026-09-13T0${8+i%2}:15:00`,driverOpenedAt:i%4===0?undefined:`2026-09-13T0${8+i%2}:20:00`,driverAcknowledgedAt:i%5===0?undefined:`2026-09-13T0${8+i%2}:22:00`}});
initialOrders[0].productId=2;initialOrders[0].amount=860;initialOrders[0].status='חדשה';
export const initialStock:Stock[] = [{id:0,name:'מחסן מרכזי',full12:284,empty12:96,full48:168,empty48:72,other:87},...Array.from({length:5},(_,i)=>({id:i+1,name:`רכב ${initialDrivers[i].name}`,full12:26-i*3,empty12:8+i*2,full48:i===1?4:24-i*2,empty48:12+i,other:8}))];
export const vehicles = Array.from({length:5},(_,i)=>({id:i+1,name:['58-123-45','67-234-56','76-345-67','85-456-78','94-567-89'][i],type:['איווקו דיילי','איסוזו סומו','מרצדס ספרינטר','פיאט דוקאטו','איווקו דיילי'][i],vehicleClass:['משאית קטנה','משאית גדולה','מסחרית','משאית קטנה','טנדר'][i],driverId:i+1,km:84210+i*17320,test:'11/10/2026',insurance:'25/09/2026',hazmat:'30/12/2026',status:i===4?'בטיפול':'פעיל',maxGasKg:5000}));
export const technicians = ['אחמד חורי','ראמי מסארווה','דוד אדרי','נאסר יונס','אייל שפירא'].map((name,i)=>({id:i+1,name,phone:`054-00000${30+i}`,certification:i%2?'מתקין גז רמה 1':'מתקין גז רמה 2',area:areas[i],status:i%2?'בקריאה':'זמין'}));
export const initialServices:Service[] = Array.from({length:10},(_,i)=>({id:3021+i,customerId:i+1,technicianId:i%5+1,type:['בדיקת מערכת גז','התקנת מחמם מים','טיפול בתקלה','החלפת וסת','בדיקת בטיחות'][i%5],date:today,time:`${9+i}:00`,status:['חדשה','שויכה','בדרך','בעבודה','הושלמה'][i%5],priority:i%3?'רגילה':'גבוהה'}));
export const suppliers = [{id:1,name:'סופרגז',taxId:'520000111',contact:'מחלקת הפצה',phone:'04-0000100'},{id:2,name:'ספק ציוד גז',taxId:'515000222',contact:'מחלקת הזמנות',phone:'04-0000200'},{id:3,name:'ספק וסתים',taxId:'204000333',contact:'שירות לקוחות',phone:'04-0000300'}];
export const priceLists = [{id:'general',name:'מחירון כללי',factor:1},{id:'business',name:'מחירון עסקי',factor:.97},{id:'service',name:'מחירון נותן שירות',factor:.9},{id:'vip',name:'מחירון VIP',factor:.95}];
export const serviceProviders = [{id:1,name:'מוחמד שירותי גז',company:'מוחמד שירותי גז בע״מ',taxId:'515123456',phone:'050-7000001',area:'ואדי ערה',priceList:'מחירון נותן שירות',taken:18400,received:12600,paid:9200},{id:2,name:'א.א. התקנות',company:'א.א. התקנות ושירות בע״מ',taxId:'514987321',phone:'050-7000002',area:'חדרה',priceList:'מחירון נותן שירות',taken:11200,received:9800,paid:7600},{id:3,name:'שירותי הצפון',company:'שירותי הצפון',taxId:'203456789',phone:'050-7000003',area:'חריש',priceList:'מחירון עסקי',taken:8600,received:7200,paid:5400}];
export const initialNotices:Notice[] = Array.from({length:15},(_,i)=>({id:i+1,title:['מוחמד לא אישר 3 הזמנות במשך 15 דקות','מלאי 48 ק״ג ברכב של עבד נמוך','6 לקוחות עברו מועד הזמנה צפוי','ביטוח רכב מסתיים בעוד 12 ימים','סנכרון מסמך פיננסי נכשל'][i%5],category:['נהגים','מלאי','לקוחות','רכבים','כספים'][i%5],severity:i%5===0?'קריטי':i%3?'תפעול':'מערכת',target:['drivers','inventory','forecast','vehicles','payments'][i%5],entityId:i%5===3?1:i%5===1?2:1,read:i>9,muted:false,deferred:false}));
export const initialAudit:Audit[] = Array.from({length:20},(_,i)=>({id:i+1,time:`${12-Math.floor(i/6)}:${String(55-i%6*8).padStart(2,'0')}`,user:['סעד','אמיר','מוחמד','אחמד'][i%4],module:['הזמנות','מוצרים','הזמנות','מלאי'][i%4],action:['שינוי נהג','עדכון מחיר','סגירת הזמנה','החזרת ריקים'][i%4],entity:String(10421+i),before:['מוחמד','₪420','בדרך','0'][i%4],after:['עבד','₪430','בוצעה','12'][i%4],device:i%2?'מחשב משרד':'טלפון נייד'}));
export const chartData = Array.from({length:30},(_,i)=>({day:String(i+1),revenue:8200+(i*1737%10000),orders:19+i*7%26,forecast:12+i*3%18}));
export const navGroups = [
 {label:'ראשי',items:[['dashboard','דשבורד הנהלה','LayoutDashboard'],['orders','הזמנות','ClipboardList'],['new-order','הזמנה חדשה','CirclePlus']]},
 {label:'הפצה',items:[['dispatch','שיבוץ נהגים','Route'],['areas','אזורי חלוקה','MapPin'],['driver-alerts','התראות נהגים','Radio'],['notifications','מרכז התראות','Bell'],['map','מפת חלוקה','Map']]},
 {label:'לקוחות',items:[['customers','לקוחות','Users'],['duplicates','כפילויות','Copy'],['categories','קטגוריות לקוחות','Tags'],['forecast','צפי הזמנות','CalendarClock']]},
 {label:'שטח',items:[['drivers','נהגים','Truck'],['service-providers','נותני שירות','Building2'],['technicians','טכנאים','Wrench'],['vehicles','רכבים','Car']]},
 {label:'מלאי',items:[['inventory','מחסן ומלאי','Warehouse'],['vehicle-audit','בדיקת מלאי רכבים יומי','ClipboardList'],['products','מוצרים ומחירונים','Package'],['suppliers','ספקים','Building2']]},
 {label:'כספים וניהול',items:[['payments','תשלומים ומסמכים','Wallet'],['profitability','רווחיות','ChartNoAxesCombined'],['reports','דוחות וניתוח נתונים','ChartNoAxesCombined'],['bonuses','יעדים ובונוסים','Target'],['employees','עובדים והרשאות','ShieldCheck']]},
 {label:'מערכת',items:[['audit','יומן פעילות','History'],['devices','משתמשים ומכשירים','MonitorSmartphone'],['support','תמיכה וניהול מערכת','LifeBuoy'],['settings','הגדרות העסק','Settings']]}
];
